# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-08 15:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UraJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('name', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='Название')),
                ('unit_id', models.PositiveIntegerField(verbose_name='idUnit')),
                ('driver_id', models.CharField(max_length=255, verbose_name='idDriver')),
                ('driver_fio', models.CharField(max_length=255, verbose_name='ФИО водителя')),
                ('date_begin', models.DateTimeField(verbose_name='Дата/время начала')),
                ('date_end', models.DateTimeField(verbose_name='Дата/время конца')),
                ('return_time', models.DateTimeField(verbose_name='Дата/время return')),
                ('leave_time', models.DateTimeField(verbose_name='Дата/время leave')),
            ],
            options={
                'verbose_name_plural': 'Заявки',
                'verbose_name': 'Заявка',
            },
        ),
    ]
