# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-14 12:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ura', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='urajob',
            name='route_id',
            field=models.PositiveIntegerField(default=0, verbose_name='idRoute'),
            preserve_default=False,
        ),
    ]
