# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-26 06:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ura', '0003_auto_20170914_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urajob',
            name='route_id',
            field=models.CharField(max_length=255, verbose_name='idRoute'),
        ),
        migrations.AlterField(
            model_name='urajob',
            name='unit_id',
            field=models.CharField(max_length=255, verbose_name='idUnit'),
        ),
    ]
