# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-09 11:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ura', '0004_auto_20170926_0622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urajob',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
    ]
