# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-11 11:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ura', '0005_auto_20171009_1116'),
    ]

    operations = [
        migrations.CreateModel(
            name='StandardJobTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('wialon_id', models.IntegerField(verbose_name='ID в Wialon')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('space_overstatements_standard', models.PositiveIntegerField(blank=True, null=True, verbose_name='Норматив перенахождения вне плановых геозон, мин.')),
            ],
            options={
                'verbose_name': 'Маршрут Wialon',
                'verbose_name_plural': 'Маршруты Wialon',
            },
        ),
        migrations.CreateModel(
            name='StandardPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('template_id', models.IntegerField(verbose_name='ID шаблона отчета (маршрута)')),
                ('wialon_id', models.IntegerField(verbose_name='ID в Wialon')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('total_time_standard', models.PositiveIntegerField(blank=True, null=True, verbose_name='Норматив времени нахождения, мин.')),
                ('parking_time_standard', models.PositiveIntegerField(blank=True, null=True, verbose_name='Норматив времени стоянок, мин.')),
            ],
            options={
                'verbose_name': 'Геозона Wialon',
                'verbose_name_plural': 'Геозоны Wialon',
            },
        ),
        migrations.CreateModel(
            name='UraJobPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок')),
                ('point_type', models.PositiveIntegerField(blank=True, null=True, verbose_name='Тип геозоны')),
                ('enter_date_time', models.DateTimeField(blank=True, null=True, verbose_name='Время входа')),
                ('leave_date_time', models.DateTimeField(blank=True, null=True, verbose_name='Время выхода')),
                ('total_time', models.FloatField(blank=True, null=True, verbose_name='Время в геозоне, сек')),
                ('parking_time', models.FloatField(blank=True, null=True, verbose_name='Время стоянки в геозоне, сек')),
            ],
            options={
                'verbose_name': 'Геозона путевого листа',
                'verbose_name_plural': 'Геозоны путевого листа',
            },
        ),
        migrations.AlterModelOptions(
            name='urajob',
            options={'verbose_name': 'Путевой лист', 'verbose_name_plural': 'Путевые листы'},
        ),
        migrations.AddField(
            model_name='urajob',
            name='execution_status',
            field=models.CharField(choices=[('not_available', 'Не исследовано'), ('not_finished', 'Не завершено'), ('finished', 'Завершено')], default='not_available', max_length=50, verbose_name='Статус прохождения (актуальности)'),
        ),
        migrations.AddField(
            model_name='urajobpoint',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='ura.UraJob', verbose_name='Путевой лист'),
        ),
    ]
