# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-12 19:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ura', '0006_auto_20171211_1152'),
    ]

    operations = [
        migrations.CreateModel(
            name='UraJobLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('request', models.TextField(verbose_name='Запрос')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log', to='ura.UraJob', verbose_name='Путевой лист')),
            ],
            options={
                'verbose_name_plural': 'Путевые листы',
                'verbose_name': 'Путевой лист',
            },
        ),
    ]
