# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-17 21:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ura', '0008_auto_20171213_0934'),
    ]

    operations = [
        migrations.AddField(
            model_name='standardpoint',
            name='job_template',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='points', to='ura.StandardJobTemplate', verbose_name='Шаблон отчетов (маршрут)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='urajobpoint',
            name='lat',
            field=models.FloatField(blank=True, null=True, verbose_name='Широта входа в геозону'),
        ),
        migrations.AddField(
            model_name='urajobpoint',
            name='lng',
            field=models.FloatField(blank=True, null=True, verbose_name='Долгота входа в геозону'),
        ),
        migrations.AlterField(
            model_name='standardjobtemplate',
            name='wialon_id',
            field=models.CharField(max_length=64, unique=True, verbose_name='ID в WIalon'),
        ),
        migrations.AlterField(
            model_name='standardpoint',
            name='wialon_id',
            field=models.CharField(max_length=64, verbose_name='ID в WIalon'),
        ),
        migrations.RemoveField(
            model_name='standardpoint',
            name='template_id',
        ),
        migrations.AlterUniqueTogether(
            name='standardpoint',
            unique_together=set([('job_template', 'wialon_id')]),
        ),
    ]
