# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-18 12:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ura', '0009_auto_20171217_2158'),
    ]

    operations = [
        migrations.AddField(
            model_name='standardjobtemplate',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='standard_job_templates', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
