# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-20 21:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ura', '0010_standardjobtemplate_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='urajob',
            name='execution_status',
        ),
        migrations.AddField(
            model_name='urajoblog',
            name='response',
            field=models.TextField(blank=True, null=True, verbose_name='Ответ'),
        ),
        migrations.AddField(
            model_name='urajoblog',
            name='response_status',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Статус ответа'),
        ),
        migrations.AlterField(
            model_name='urajoblog',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='log', to='ura.UraJob', verbose_name='Путевой лист'),
        ),
        migrations.AlterField(
            model_name='urajoblog',
            name='request',
            field=models.TextField(blank=True, null=True, verbose_name='Запрос'),
        ),
    ]
