# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-21 11:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ura', '0011_auto_20171220_2103'),
    ]

    operations = [
        migrations.AddField(
            model_name='urajoblog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
