# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-28 20:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ura', '0013_auto_20171221_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standardjobtemplate',
            name='space_overstatements_standard',
            field=models.FloatField(blank=True, null=True, verbose_name='Норматив перенахождения вне плановых геозон, мин.'),
        ),
        migrations.AlterField(
            model_name='standardpoint',
            name='parking_time_standard',
            field=models.FloatField(blank=True, null=True, verbose_name='Норматив времени стоянок, мин.'),
        ),
        migrations.AlterField(
            model_name='standardpoint',
            name='total_time_standard',
            field=models.FloatField(blank=True, null=True, verbose_name='Норматив времени нахождения, мин.'),
        ),
    ]
