# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-09 12:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ura', '0015_urajob_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urajoblog',
            name='url',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='URL'),
        ),
    ]
