# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-07-04 14:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ura', '0023_auto_20180703_1542'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobpointstop',
            name='job_point',
        ),
        migrations.DeleteModel(
            name='JobPointStop',
        ),
    ]
