default_app_config = 'reports.apps.AppConfig'


DEFAULT_TOTAL_TIME_STANDARD_MINUTES = 3
DEFAULT_PARKING_TIME_STANDARD_MINUTES = 3
DEFAULT_SPACE_TOTAL_TIME_STANDARD_MINUTES = 3
DEFAULT_OVERSTATEMENT_NORMAL_PERCENTAGE = 5
DEFAULT_OVERSPANDING_NORMAL_PERCENTAGE = 5
