# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-17 11:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Redirect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('ordering', models.IntegerField(db_index=True, default=0, verbose_name='Порядок')),
                ('status', models.SmallIntegerField(choices=[(0, 'Черновик'), (1, 'Публичный'), (2, 'Скрытый')], default=1, verbose_name='Статус')),
                ('old_path', models.TextField(db_index=True, max_length=1024, unique=True, verbose_name='Откуда')),
                ('new_path', models.TextField(max_length=1024, verbose_name='Куда')),
                ('http_code', models.PositiveIntegerField(choices=[(304, '304'), (305, '305'), (306, '306'), (307, '307'), (410, '410'), (301, '301'), (302, '302'), (303, '303')], default=301, verbose_name='Код состояния')),
            ],
            options={
                'verbose_name': 'Редирект',
                'verbose_name_plural': 'Редиректы',
            },
        ),
        migrations.CreateModel(
            name='Robot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('ordering', models.IntegerField(db_index=True, default=0, verbose_name='Порядок')),
                ('status', models.SmallIntegerField(choices=[(0, 'Черновик'), (1, 'Публичный'), (2, 'Скрытый')], default=1, verbose_name='Статус')),
                ('title', models.CharField(max_length=254, verbose_name='Имя робота')),
                ('host', models.CharField(blank=True, max_length=254, null=True, verbose_name='Host')),
                ('crawl_delay', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Crawl-delay')),
            ],
            options={
                'verbose_name': 'Робот (User-agent)',
                'verbose_name_plural': 'Robots.txt',
            },
        ),
        migrations.CreateModel(
            name='RobotAllow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('ordering', models.IntegerField(db_index=True, default=0, verbose_name='Порядок')),
                ('status', models.SmallIntegerField(choices=[(0, 'Черновик'), (1, 'Публичный'), (2, 'Скрытый')], default=1, verbose_name='Статус')),
                ('url_pattern', models.CharField(max_length=254, verbose_name='Шаблон ссылки')),
                ('robot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allows', to='seo.Robot', verbose_name='Робот')),
            ],
            options={
                'verbose_name': 'Allow',
                'verbose_name_plural': 'Allow (Разрешения)',
            },
        ),
        migrations.CreateModel(
            name='RobotCleanparam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('ordering', models.IntegerField(db_index=True, default=0, verbose_name='Порядок')),
                ('status', models.SmallIntegerField(choices=[(0, 'Черновик'), (1, 'Публичный'), (2, 'Скрытый')], default=1, verbose_name='Статус')),
                ('params', models.CharField(max_length=254, verbose_name='Параметры')),
                ('url_pattern', models.CharField(max_length=254, verbose_name='Шаблон ссылки')),
                ('robot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clean_params', to='seo.Robot', verbose_name='Робот')),
            ],
            options={
                'verbose_name': 'Clean-param',
                'verbose_name_plural': 'Параметры Clean-param',
            },
        ),
        migrations.CreateModel(
            name='RobotDisallow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('ordering', models.IntegerField(db_index=True, default=0, verbose_name='Порядок')),
                ('status', models.SmallIntegerField(choices=[(0, 'Черновик'), (1, 'Публичный'), (2, 'Скрытый')], default=1, verbose_name='Статус')),
                ('url_pattern', models.CharField(max_length=254, verbose_name='Шаблон (ссылка)')),
                ('robot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disallows', to='seo.Robot', verbose_name='Робот')),
            ],
            options={
                'verbose_name': 'Disallow',
                'verbose_name_plural': 'Disallow (Запреты)',
            },
        ),
        migrations.CreateModel(
            name='RobotSitemap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('ordering', models.IntegerField(db_index=True, default=0, verbose_name='Порядок')),
                ('status', models.SmallIntegerField(choices=[(0, 'Черновик'), (1, 'Публичный'), (2, 'Скрытый')], default=1, verbose_name='Статус')),
                ('url', models.CharField(max_length=254, verbose_name='Sitemap')),
                ('robot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sitemaps', to='seo.Robot', verbose_name='Робот')),
            ],
            options={
                'verbose_name': 'Sitemap',
                'verbose_name_plural': 'Sitemap (Карты сайта XML)',
            },
        ),
        migrations.CreateModel(
            name='SEOPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('ordering', models.IntegerField(db_index=True, default=0, verbose_name='Порядок')),
                ('status', models.SmallIntegerField(choices=[(0, 'Черновик'), (1, 'Публичный'), (2, 'Скрытый')], default=1, verbose_name='Статус')),
                ('seo_title', models.CharField(blank=True, max_length=254, null=True, verbose_name='SEO Заголовок (title)')),
                ('seo_description', models.TextField(blank=True, null=True, verbose_name='META Description')),
                ('seo_keywords', models.TextField(blank=True, null=True, verbose_name='META Keywords')),
                ('url', models.CharField(blank=True, db_index=True, help_text='Введите URL страницы, параметры которой хотите переопределить, без указания домена и языка! Например, /about/', max_length=255, unique=True, verbose_name='Ссылка (URL)')),
            ],
            options={
                'verbose_name': 'SEO параметр',
                'verbose_name_plural': 'SEO параметры',
            },
        ),
    ]
