# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-19 09:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20170914_1126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='org_id',
        ),
        migrations.AddField(
            model_name='user',
            name='organization_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Название организации в Wialon'),
        ),
        migrations.AddField(
            model_name='user',
            name='supervisor_id',
            field=models.ForeignKey(blank=True, help_text='Указание супервайзера позволит УРА работать сразу с несколькими учетными записями под одним логин/паролем', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Супервайзер'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Имя ответственного лица'),
        ),
        migrations.AlterField(
            model_name='user',
            name='full_name',
            field=models.TextField(blank=True, max_length=500, verbose_name='ФИО ответственного лица'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Фамилия ответственного лица'),
        ),
        migrations.AlterField(
            model_name='user',
            name='middle_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Отчество ответственного лица'),
        ),
    ]
