# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-19 10:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20170919_0925'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='supervisor_id',
            new_name='supervisor',
        ),
    ]
