# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-21 10:00
from __future__ import unicode_literals

from django.db import migrations
import timezone_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20170919_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ura_tz',
            field=timezone_field.fields.TimeZoneField(default='UTC', verbose_name='Часовой пояс УРА'),
        ),
        migrations.AddField(
            model_name='user',
            name='wialon_tz',
            field=timezone_field.fields.TimeZoneField(default='UTC', verbose_name='Часовой пояс Wialon'),
        ),
    ]
