# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-01 17:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20170926_1937'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='wialon_geozones_report_template_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='ID отчета "Геозоны" в Wialon'),
        ),
    ]
