# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-20 09:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20171120_0836'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='wialon_username',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Логин в Wialon'),
        ),
    ]
