# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 07:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20171120_1010'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='wialon_password',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Пароль в Wialon'),
        ),
    ]
