# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-16 17:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_user_wialon_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='wialon_report_object_id',
        ),
        migrations.AddField(
            model_name='user',
            name='wialon_group_object_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Наименование группового объекта'),
        ),
    ]
