# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-16 17:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20171216_1742'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='wialon_report_resource_id',
        ),
        migrations.AddField(
            model_name='user',
            name='wialon_resource_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Наименование ресурса'),
        ),
    ]
