# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-16 19:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20171216_1758'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='wialon_discharge_report_template_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='wialon_driving_style_report_template_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='wialon_geozones_report_template_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='wialon_kmu_report_template_id',
        ),
        migrations.AddField(
            model_name='user',
            name='wialon_discharge_report_template_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Наименование отчета "Перерасход топлива"'),
        ),
        migrations.AddField(
            model_name='user',
            name='wialon_driving_style_report_template_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Наименование отчета "Стиль вождения (ПДД)"'),
        ),
        migrations.AddField(
            model_name='user',
            name='wialon_geozones_report_template_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Наименование отчета "Геозоны"'),
        ),
        migrations.AddField(
            model_name='user',
            name='wialon_kmu_report_template_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Наименование отчета "Работа крановой установки"'),
        ),
    ]
