# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-28 14:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_auto_20180225_2220'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='wialon_sensors_report_template_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Наименование отчета "Неисправности"'),
        ),
    ]
