# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-28 20:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_user_wialon_sensors_report_template_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='wialon_last_data_report_template_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Наименование отчета "Последние данные"'),
        ),
    ]
