# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-01 11:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_user_wialon_last_data_report_template_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ura_standards_for_user',
            field=models.ForeignKey(blank=True, help_text='В случае отсутствия будет показывать все нормативы', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supervisored_users_for_standards', to=settings.AUTH_USER_MODEL, verbose_name='Просмотр нормативов от лица пользователя'),
        ),
    ]
