# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-01 19:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_user_ura_standards_for_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='wialon_driving_style_individual_report_template_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Наименование отчета "Качество вождения индивидуальный (БДД)"'),
        ),
        migrations.AlterField(
            model_name='user',
            name='wialon_driving_style_report_template_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Наименование отчета "Качество вождения (БДД)"'),
        ),
    ]
