# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-02 07:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_auto_20180301_1939'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='ura_standards_for_user',
        ),
        migrations.AddField(
            model_name='user',
            name='ura_user',
            field=models.ForeignKey(blank=True, help_text='В случае отсутствия будет показывать все данные УРА (ПЛ, нормативы). При задании позволяет операторам получать отчеты от лица головной учетной записи', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ura_subordinates', to=settings.AUTH_USER_MODEL, verbose_name='Просмотр данных УРА от лица пользователя УРА'),
        ),
    ]
