# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-06 12:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_auto_20180305_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='wialon_mobile_vehicle_types',
            field=models.CharField(blank=True, help_text='Через ЗАПЯТУЮ. Пробелы между типами и регистр значения не имеют. Если не указан список типов, допускаем наличие любых ТС в отчетах по ПДД. Объекты, у которых в характеристиках не указан тип ТС, также включаются в отчеты.', max_length=255, null=True, verbose_name='Список мобильных типов ТС, по которым необходимы отчеты ПДД'),
        ),
    ]
