# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-06-12 14:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_user_wialon_mobile_vehicle_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='supervisor',
            field=models.ForeignKey(blank=True, help_text='Указание супервайзера позволит УРА работать сразу с несколькими учетными записями под одним логин/паролем', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Супервайзер'),
        ),
        migrations.AlterField(
            model_name='user',
            name='ura_user',
            field=models.ForeignKey(blank=True, help_text='В случае отсутствия будет показывать все данные УРА (ПЛ, нормативы). При задании позволяет операторам получать отчеты от лица головной учетной записи', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ura_subordinates', to=settings.AUTH_USER_MODEL, verbose_name='Просмотр данных УРА от лица пользователя УРА'),
        ),
    ]
