# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-06-22 13:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_auto_20180612_1406'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='wialon_discharge_report_template_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='wialon_kmu_report_template_name',
        ),
        migrations.AddField(
            model_name='user',
            name='wialon_taxiing_report_template_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Наименование отчета "Таксировка"'),
        ),
    ]
