# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-07-03 09:22
from __future__ import unicode_literals

import timezone_field
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_auto_20180622_1328'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='wialon_tz',
            new_name='timezone',
        ),
        migrations.RemoveField(
            model_name='user',
            name='ura_tz',
        ),
        migrations.AlterField(
            model_name='user',
            name='timezone',
            field=timezone_field.fields.TimeZoneField(default='UTC', verbose_name='Часовой пояс'),
        )
    ]
