# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-12-13 10:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_auto_20180703_0922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(blank=True, help_text='Можно указать через запятую', max_length=255, verbose_name='email address'),
        ),
    ]
