# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-02-07 13:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_auto_20181213_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='total_report_users',
            field=models.ManyToManyField(blank=True, related_name='_user_total_report_users_+', to=settings.AUTH_USER_MODEL, verbose_name='Подчиненные пользователи для сводных отчетов'),
        ),
    ]
