# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-11-06 10:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reports', '0003_auto_20180318_2219'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrivingStyleReportDelivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('ordering', models.IntegerField(db_index=True, default=0, verbose_name='Порядок')),
                ('status', models.SmallIntegerField(choices=[(0, 'Черновик'), (1, 'Публичный'), (2, 'Скрытый')], default=1, verbose_name='Статус')),
                ('work_title', models.CharField(max_length=255, verbose_name='Рабочее название настроек')),
                ('users', models.ManyToManyField(related_name='driving_style_report_delivery_settings', to=settings.AUTH_USER_MODEL, verbose_name='Пользователи')),
            ],
            options={
                'verbose_name': 'Настройка рассылки отчета "Качество вождения"',
                'verbose_name_plural': 'Настройка рассылок отчета "Качество вождения"',
            },
        ),
        migrations.CreateModel(
            name='FaultsReportDelivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('ordering', models.IntegerField(db_index=True, default=0, verbose_name='Порядок')),
                ('status', models.SmallIntegerField(choices=[(0, 'Черновик'), (1, 'Публичный'), (2, 'Скрытый')], default=1, verbose_name='Статус')),
                ('work_title', models.CharField(max_length=255, verbose_name='Рабочее название настроек')),
                ('job_extra_offset', models.PositiveSmallIntegerField(default=2, verbose_name='Дополнительное время до и после ПЛ, ч')),
                ('users', models.ManyToManyField(related_name='faults_report_delivery_settings', to=settings.AUTH_USER_MODEL, verbose_name='Пользователи')),
            ],
            options={
                'verbose_name': 'Настройка рассылки отчета "Состояние оборудования"',
                'verbose_name_plural': 'Настройка рассылок отчета "Состояние оборудования"',
            },
        ),
    ]
