# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-11-12 08:34
from __future__ import unicode_literals

from django.db import migrations, models


def get_full_name(user):
    fn = ' '.join(filter(lambda x: x, (user.first_name, user.last_name)))
    return fn if fn else user.username


def forwards_func(apps, schema_editor):
    from reports.enums import EmailDeliveryReportTypeEnum
    log_model = apps.get_model('reports', 'ReportEmailDeliveryLog')
    for log in log_model.objects.all():
        if log.report_type == EmailDeliveryReportTypeEnum.DRIVING_STYLE:
            log.subject = 'Отчет о качестве вождения (ВЧМ)'
        elif log.report_type == EmailDeliveryReportTypeEnum.FAULTS:
            log.subject = 'Ежедневный отчет о состоянии оборудования'

        log.body = 'Здравствуйте, %s. Отчет по вложении.' % get_full_name(log.user)
        log.save()


def backwards_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_auto_20181106_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportemaildeliverylog',
            name='body',
            field=models.TextField(default='', verbose_name='Текст письма'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reportemaildeliverylog',
            name='error_message',
            field=models.TextField(blank=True, null=True, verbose_name='Текст ошибки'),
        ),
        migrations.AddField(
            model_name='reportemaildeliverylog',
            name='subject',
            field=models.CharField(default='', max_length=255, verbose_name='Тема письма'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reportemaildeliverylog',
            name='success',
            field=models.BooleanField(default=False, verbose_name='Удачно'),
        ),
        migrations.RunPython(forwards_func, backwards_func)
    ]
