# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-02-07 14:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reports', '0007_auto_20181112_0834'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrivingStyleTotalReportDelivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('ordering', models.IntegerField(db_index=True, default=0, verbose_name='Порядок')),
                ('status', models.SmallIntegerField(choices=[(0, 'Черновик'), (1, 'Публичный'), (2, 'Скрытый')], default=1, verbose_name='Статус')),
                ('work_title', models.CharField(max_length=255, verbose_name='Рабочее название настроек')),
                ('users', models.ManyToManyField(related_name='driving_style_total_report_delivery_settings', to=settings.AUTH_USER_MODEL, verbose_name='Пользователи')),
            ],
            options={
                'verbose_name': 'Настройка рассылки отчета "Качество вождения (Сводный)"',
                'verbose_name_plural': 'Настройка рассылок отчета "Качество вождения (Сводный)"',
            },
        ),
    ]
