# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-17 11:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DbConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('ordering', models.IntegerField(db_index=True, default=0, verbose_name='Порядок')),
                ('status', models.SmallIntegerField(choices=[(0, 'Черновик'), (1, 'Публичный'), (2, 'Скрытый')], default=1, verbose_name='Статус')),
                ('key', models.CharField(db_index=True, max_length=250, unique=True, verbose_name='Ключ')),
                ('verbose_title', models.CharField(max_length=250, verbose_name='Что означает')),
                ('value', models.TextField(blank=True, verbose_name='Значение')),
            ],
            options={
                'verbose_name_plural': 'Переменные шаблонов',
                'verbose_name': 'Переменная',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('ordering', models.IntegerField(db_index=True, default=0, verbose_name='Порядок')),
                ('status', models.SmallIntegerField(choices=[(0, 'Черновик'), (1, 'Публичный'), (2, 'Скрытый')], default=1, verbose_name='Статус')),
                ('slug', models.SlugField(unique=True, verbose_name='Алиас')),
                ('title', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name_plural': 'Меню',
                'verbose_name': 'Меню',
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('ordering', models.IntegerField(db_index=True, default=0, verbose_name='Порядок')),
                ('status', models.SmallIntegerField(choices=[(0, 'Черновик'), (1, 'Публичный'), (2, 'Скрытый')], default=1, verbose_name='Статус')),
                ('li_class_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='CSS-класс (li тэг)')),
                ('a_class_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='CSS-класс for link (a тэг)')),
                ('url', models.CharField(max_length=255, verbose_name='Ссылка')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Заголовок')),
                ('alt', models.CharField(blank=True, max_length=255, null=True, verbose_name='Текст при наведении')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='general.Menu', verbose_name='Меню')),
                ('parent_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='general.MenuItem', verbose_name='Родительский пункт меню')),
            ],
            options={
                'verbose_name_plural': 'Пункты меню',
                'verbose_name': 'Пункт меню',
            },
        ),
    ]
